### ISSUE TITLE
Invalid token on save

### ISSUE THREAD

**Issue by dragonito** [tolry/mental-note#13]
There is a invalid token message on save.

When you add a tag with "enter" and click the save button with the mouse.

**Comment by tolry** [comment]
Could not reproduce as mentioned above. Could this be a session issue?

* was the modal dialog open a long time?
* have you been idle and therefore logged out before submitting the form?

**Comment by dragonito** [comment]
I think it comes when you login to mentalnote and directly add a Link with two tags in press save.

**Comment by tolry** [comment]
Sorry, but I still cannot reproduce this.

What I am doing

* logout
* login
* press "add link"
* enter the uri
* wait for the metainfo to load
* enter two tags (completely by keyboard, no mouse interaction)
* press the save link either by mouse or navigate by 'tab' an submit by space

Since the form is loaded via a AJAX GET request I am suspecting the browser cache to be a possible source of this. Does this problem happen on different browsers or just the single one. If that's the case, which browser are you using?

**Comment by dragonito** [comment]
MMM really strange Problem. Perhaps this helps

https://www.youtube.com/watch?v=k-sMN74YdY0

**Comment by tolry** [comment]
OK, I've uploaded a possible hotfix for this, I am now appending unix epoch seconds to the ajax url, hopefully preventing safari from caching the ajax request and returning an outdated form with an outdated csrf token.

Pls do a force reload and try again - if this is successful I will make a proper patch.

**Comment by dragonito** [comment]
I use Chrome :) Error is still there

**Comment by tolry** [comment]
OK, I am out of ideas right now - would you please check, if the ajax call to create.html has a "?t=12345" appended to it?

Can you see any pattern in the occurrence of this bug:

* does it happen every time you add an entry?
* every 10th time?
* only the first "add entry" after login / remember me cookie logging you in?
* totally random?
* does it happen only on this one machine?
* does it happen in other browsers on the same machine (safari, firefox, ...)?
* how do you solve this issue, when it occurs?
* can you reproduce this bug in your dev installation (if you have one)?

I had a look at the nginx logs already, but as far as I can see there is a GET request to create.html before the POST create.html happens.

**Comment by dragonito** [comment]
It happens after first login of a day. Cookies where removed on browser close! And it comes when i do adding fast. Copy URL, jumping directly to tag, autocomplete it and press save. It happens on chrome (Win and MacOs). A second click to save solves this error.

I dont have a dev-installation in this time, but i could install it :)

This error does not come if the cache is not cleared when browser closes!

**Comment by tolry** [comment]
Any news on this, @davidbadura told me a while ago, that he also shortly experienced the problem. I still am not able to reproduce this.

**Comment by tolry** [comment]
I had a silly bug when using remember-me-Cookies for mental note, resulting in remember me functionality not working :grin:  (fixed in https://github.com/tolry/mental-note/commit/aba604d7c20d0b74b85b52a9e8a9d5b00d50036e)

Maybe this problem is resolved by this too, or at least doesn't show anymore, if you use mental note at least once a week (expiry duration of remember me cookie).

**Comment by dragonito** [comment]
Mmm nice :) it works, hope also for the future ;)

**Comment by DavidBadura** [comment]
:+1:

**Comment by tolry** [comment]
Well, that was easy ... :wink:
