### ISSUE TITLE
Already added links

### ISSUE THREAD

**Issue by dragonito** [tolry/mental-note#5]
Inform user about already added links.

Extend:
Perhaps change from read to unread state automaticly when a link added a second time

**Comment by tolry** [comment]
Definitely: check fur duplicity should be done on the ajax request while adding a link. I don't know about the other logic: if I enter a URL that has already been entered for this user, it should simply not be allowed.

Otherwise the user would click on "add link" and as a result, he would edit a link, plus what would be done with discrepancies in tags, category and description? I think it would be quite hard to let the user understand, what is happening here and why.

**Comment by dragonito** [comment]
Perhaps inform the user and let him change the state to unread with one click.

**Comment by tolry** [comment]
Commit 037b27164bc27e90f96585c0f98707ff617d18b5 at least fixes the warning being displayed properly, no immediate AJAX feedback yet. But no longer 500 - that's at least progress, right?
